---
# This Playbook would deploy following roles.
- hosts: all_hosts
  become: yes
  roles:
  - { role: 'reboot', tags: 'reboot' }
  - { role: minimize_access, tags: 'Changes' }
  - { role: rhosts, tags: 'security'}
  - { role: apt, tags: 'security'}
  - { role: revert, tags: 'rollback' }

