---
- name: Get user accounts
  command: "awk -F: '{print $1}' /etc/passwd"
  changed_when: False
  check_mode: False
  register: users_accounts

- name: delete rhosts-files from system
  file:
    dest: '~{{ item }}/.rhosts'
    state: 'absent'
  with_flattened: '{{ users_accounts.stdout_lines | default([]) }}'

- name: delete hosts.equiv from system
  file:
    dest: '/etc/hosts.equiv'
    state: 'absent'

- name: delete .netrc-files from system
  file:
    dest: '~{{ item }}/.netrc'
    state: 'absent'
  with_flattened: '{{ users_accounts.stdout_lines | default([]) }}'
